apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: clickhouse
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      database: kube_cost
      port: 8123
      protocol: http
      username: grafana_reader
    secureJsonData:
      password: grafana_reader
