image:
  repository: kube-cost/agent
  tag: dev
  pullPolicy: IfNotPresent

agent:
  tenantId: local
  clusterId: local-kind
  ingestionEndpoint: kube-cost-platform-ingestion.kube-cost-system.svc:8080
  insecureGRPC: false
  leaderElection: true
  inventoryResyncInterval: 30m
  queueCapacity: 10000
  batchSize: 200

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
