imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 24Mi
  limits:
    cpu: 100m
    memory: 96Mi

ingestion:
  insecure: true
  clickhouse:
    address: host.docker.internal:9000
